### ISSUE TITLE
Build with Visual Studio 2022 17.2.1

### ISSUE THREAD

**Issue by Philippe91** [alandefreitas/small#21]
Did you try to build with the latest MSVC ? Here it fails while building the supplied small example project, with some strange errors like:

```
1>D:\small\include\small/vector.hpp(410,1): error C2065: 'is_invocable_v': undeclared identifier
1>D:\small\include\small/vector.hpp(1729): message : see reference to class template instantiation 'small::vector<T,N,Allocator,AllowHeap,SizeType,GrowthFactor>' being compiled
1>D:\small\include\small/vector.hpp(410,74): error C2988: unrecognizable template declaration/definition
```

**Comment by alandefreitas** [comment]
> is_invocable_v is available, simply the compiler message is misleading. 

Mmm... that shouldn't be happening. I'll have a closer look at that.

> You should consider C++20 concepts rather than SFINAE ;)

Yep. C++20 concepts are nice, but I don't want to drop support for C++17 or maintain duplicated code at this point. We might be able to iteratively rewrite the most important concepts though.

**Comment by alandefreitas** [comment]
I just downloaded the latest MSVC locally and all the tests worked fine. The MSVC tests on CI are also OK. Are you sure your project settings aren't using C++11 or C++14? `is_invocable` is only available in C++17, so this is the only guess I have left.

**Comment by Philippe91** [comment]
You are right, CMake had set the project to C++14 and not C++17, hence the problem.

Usually, I run the following simple CMake command at the root of the project, and this sets everything fine:

`cmake -S . -B .\build`

But this fails at some stage for the 'small' project.
Applying this command to the examples folder would generate MSVC projects, but without the c++17 tag. This is what I tried.

Hence the problem ends up as a CMake configuration issue.

BTW, I note that if I set the compatibility to c++20 and not c++17, tons of compiler errors happen.
